# config.yaml

# Dataset configuration
dataset:
  name: "Million AID"
  data_dir: "./data/million_aid"  # Directory where the dataset will be stored
  batch_size: 32
  train_split: 0.8
  transform:
    resize: [224, 224]
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Model configuration
model:
  name: "SwinViT"
  pretrained_model: "microsoft/swin-tiny-patch4-window7-224"  # Swin ViT model for ImageNet
  num_classes: 50 #10  # Set this to match the classes in Million AID or adjust accordingly

# Training configuration
training:
  epochs: 2 #20
  lr: 0.001
  optimizer: "Adam"
  scheduler:
    name: "StepLR"
    step_size: 7
    gamma: 0.1
  device: "cuda"  # Use "cuda" if you have a GPU; otherwise, "cpu"
